spring:
     datasource:
              url: jdbc:mysql://localhost:3308/jsonwebtoken?createDatabaseIfNotExist=true&autoReconnect=true
              username: root
              password: root
     jpa:
       hibernate:
             ddl-auto: create-drop
       show-sql: true
       properties:
              :hibernate:
                       :format_sql: true
                       
#jwt
jwt:
  secret: jwtinsue
                       
                       
       