spring:
     datasource:
              url: jdbc:mysql://localhost:3308/custom_id?createDatabaseIfNotExist=true&autoReconnect=true
              username: root
              password: root
                   
     jpa:
       hibernate:
             ddl-auto: update
       show-sql: true
       properties:
              :hibernate:
                       :format_sql: true