spring:
     datasource:
              url: jdbc:mysql://localhost:3308/teacher_student?autoReconnect=true
              username: root
              password: root
     jpa:
       hibernate:
             ddl-auto: update
       show-sql: true
       properties:
              :hibernate:
                       :format_sql: true
       